#!/usr/bin/env ruby

require 'socket'

class IRC
    def initialize(server, nick, password, channel, port = 6667)
        @server = server
        @nick = nick
        @password = password
        @channel = channel
        @port = port
        @socket = nil
    end

    def connect()
        @socket = TCPSocket.open(@server, @port)
        send "NICK #{@nick}"
        send "USER #{@nick} 0 * #{@nick}"
        send "PRIVMSG NickServ :IDENTIFY #{@password}"
        send "JOIN #{@channel}"
        send "PRIVMSG #{@channel} :hello"
    end

    def send(message)
        @socket.puts(message)
    end

    def say(message)
        send "PRIVMSG #{@channel} :#{message}"
    end

    def handle_ping(message)
        if message.match(/^PING :(.*)$/)
            send "PONG #{$~[1]}"
            return true
        end

        return false
    end

    def handle_doot(message)
        if message.match(/PRIVMSG #{@channel} :(.*)$/)
            body = $~[1]

            doot_regex = /\b.oo.\b/
            if body.match(doot_regex)
                body = body.gsub(doot_regex, 'doot')
                say body
            end
            return true
        end

        return false
    end

    def loop()
        until @socket.eof? do
            message = @socket.gets
            puts message

            [:handle_ping, :handle_doot].each do |m|
                break if method(m).call(message)
            end
        end
    end
end

doot = IRC.new('irc.freenode.net', 'dootmachine', 'hunter2', '##doottesting')

doot.connect()
doot.loop()
