#!/usr/bin/env ruby

require 'socket'

class IRC
    def initialize(server, nick, channel, port = 6667)
        @server = server
        @nick = nick
        @channel = channel
        @port = port
        @socket = nil
    end

    def connect()
        @socket = TCPSocket.open(@server, @port)
        send "NICK #{@nick}"
        send "USER #{@nick} 0 * #{@nick}"
        send "JOIN #{@channel}"
        send "PRIVMSG #{@channel} :hello"
    end

    def send(message)
        @socket.puts(message)
    end

    def handle_ping(message)
        if message.match(/^PING :(.*)$/)
            send "PONG #{$~[1]}"
            return true
        end

        return false
    end

    def loop()
        until @socket.eof? do
            message = @socket.gets
            puts message

            [method(:handle_ping)].each do |m|
                m.call(message)
            end
        end
    end
end

doot = IRC.new('irc.freenode.net', 'dootmachine', '##doottesting')

doot.connect()
doot.loop()
